name: app_birthday
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.1.1 # Essencial para inicializar o Firebase
  firebase_auth: ^6.1.0 # Para autenticação
  cloud_firestore: ^6.0.2 # Banco de dados em tempo real
  firebase_storage: ^13.0.2 # Para armazenamento de fotos
  image_picker: ^1.2.0 # Para selecionar fotos da galeria/câmera
  flutter_staggered_animations: ^1.1.1 # Para animações
  google_fonts: ^6.3.2 # Para usar fontes do Google

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4 # Para ícones personalizados
flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png" # Caminho para a sua imagem
  min_sdk_android: 21 # opcional
