// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXabIT3xNd0kRIw6App_vGTZQ1F7G2xvE',
    appId: '1:530606058421:android:3440a6d140fad7f8c247fc',
    messagingSenderId: '530606058421',
    projectId: 'appbirthday2025',
    storageBucket: 'appbirthday2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEebBYMaNjVCiCKjVm5nLdcvcEHQzyqMY',
    appId: '1:530606058421:ios:6fbd1ae47632e850c247fc',
    messagingSenderId: '530606058421',
    projectId: 'appbirthday2025',
    storageBucket: 'appbirthday2025.firebasestorage.app',
    iosBundleId: 'com.example.appBirthday',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGUcWrVgqgKd5Eq5Pv_NjReTmAkK_iIaQ',
    appId: '1:530606058421:web:0a42a77b5d47c58bc247fc',
    messagingSenderId: '530606058421',
    projectId: 'appbirthday2025',
    authDomain: 'appbirthday2025.firebaseapp.com',
    storageBucket: 'appbirthday2025.firebasestorage.app',
    measurementId: 'G-ZH0VJ65SCH',
  );

}